name: Release

on:
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    name: Build and Push to production
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: sh

    permissions:
      contents: write # Needed to push changes to the repository

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: true

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up credentials
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Install dependencies
        run: npm clean-install --omit=dev

      - name: Checkout to production
        run: git checkout -B production

      - name: Update version
        run: |
          echo "${RELEASE_TAG_NAME}" > version
          git add -f version
        env:
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}

      - name: Run build
        run: npm run-script build
        env:
          NODE_ENV: ${{ vars.NODE_ENV }}
          DIST_URL: ${{ vars.DIST_URL }}
          USERSCRIPT_NAME: ${{ vars.USERSCRIPT_NAME }}
          USERSCRIPT_ICON_URL: ${{ vars.USERSCRIPT_ICON_URL }}
          USERSCRIPT_FILENAME: ${{ vars.USERSCRIPT_FILENAME }}

      - name: Add dist directory
        run: git add -f dist

      - name: Commit files
        run: |
          git commit -m "Release: ${RELEASE_TAG_NAME}" | echo
        env:
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}

      # We need to add a new tag so that it points to the newest build.
      # Since that's how we do cache busting on cdn
      - name: Change tag
        run: |
          RELEASE_TITLE=$(gh release view "${RELEASE_TAG_NAME}" --json name --template "{{.name}}")
          RELEASE_DESC=$(gh release view "${RELEASE_TAG_NAME}" --json body --template "{{.body}}")

          git tag -f -a "releases/${RELEASE_TAG_NAME}" -m "${RELEASE_TITLE}" -m "${RELEASE_DESC}"
        env:
          GITHUB_USER: <ORG>
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}

      - name: Push changes
        run: |
          git push --set-upstream origin production --force
          git push origin "releases/${RELEASE_TAG_NAME}" --force
        env:
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
